services:
  - type: static_site
    name: gps-tracker-dashboard
    env: static
    buildCommand: echo "No build needed"
    staticPublishPath: ./
    routes:
      - type: static
        path: /static
      - type: rewrite
        source: /*
        destination: /index.html